# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_rest',
            name='edi',
            field=models.CharField(default='ahmed', max_length=10),
        ),
    ]
