# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_table_rest_edi'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_rest',
            name='varr',
            field=models.IntegerField(default=33),
        ),
    ]
