# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_table_rest_varr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_rest',
            name='edi',
            field=models.CharField(default='ahmed', max_length=1000),
        ),
    ]
