# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20160904_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_rest',
            name='tt',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
